services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb
    volumes:
      - db-photo-upload-service:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8001:8001'
    depends_on:
      - database
    volumes:
      - .:/app

volumes:
  db-photo-upload-service: